---
- hosts: [HOSTS]
  user: root
  become: true
  become_user: root
  become_method: sudo
  vars:
    username: [USER_ACCOUNT]
    password: [USER_PASSWORD]
    public_key: [PUBKEY_FOR_SSH_LOGIN]
    sudoers:
      - [USER_ACCOUNT]
    ipsec_psk: "{{ lookup('file', 'ipsec.psk') }}"
  roles: 
    - common
    - user
    - wheel
    - ohmyzsh
    - timezone
    - ufw
    - ssh
    - python
    - vpn