- name: add python 3.6 PPA
  apt_repository:
    repo: "ppa:jonathonf/python-3.6"
    state: present

- name: Install python packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
    - python3.6

- name: Install global python requirements
  pip: name={{item}} state=present
  with_items:
    - pip
    - virtualenv
    - virtualenvwrapper