---
- name: Install openswan, xl2tpd, ppp, lsof
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - openswan
    - xl2tpd
    - ppp
    - lsof

- name: Set sysctl.conf
  lineinfile: 
    dest: /etc/sysctl.conf
    line: "{{ item }}"
    backup: yes
  with_items:
    - "net.ipv4.ip_forward = 1"
    - "net.ipv4.conf.all.accept_redirects = 0"
    - "net.ipv4.conf.all.send_redirects = 0"
    - "net.ipv4.conf.default.rp_filter = 0"
    - "net.ipv4.conf.default.accept_source_route = 0"
    - "net.ipv4.conf.default.send_redirects = 0"
    - "net.ipv4.icmp_ignore_bogus_error_responses = 1"

- name: Apply sysctl changes
  command: /sbin/sysctl -p

- name: Set rc.local
  template: 
    src: rc.local.j2
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0644

- name: Setup IPSec config file
  template: 
    src: ipsec.conf.j2
    dest: /etc/ipsec.conf
    owner: root
    group: root
    mode: 0644

- name: Setup IPsec shared secret
  template: 
    src: ipsec.secrets.j2
    dest: /etc/ipsec.secrets
    owner: root
    group: root
    mode: 0600

- name: Setup xl2ptd
  template: 
    src: xl2tpd.conf.j2
    dest: /etc/xl2tpd/xl2tpd.conf
    owner: root
    group: root
    mode: 0644

- name: Setup xl2tpd options
  template:
    src: options.xl2tpd.j2
    dest: /etc/ppp/options.xl2tpd
    owner: root
    group: root
    mode: 0644

- name: Setup chap-secrets
  template:
    src: chap-secrets.j2
    dest: /etc/ppp/chap-secrets
    owner: root
    group: root
    mode: 0600

- name: Restart pppd-dns, xl2tpd, ipsec
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - pppd-dns
    - xl2tpd
    - ipsec