---
- name: Upgrade packages
  apt: upgrade=safe
  
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - fail2ban
    - git-core
    - ufw
    - vim
    - ncdu
    - autojump